Add secondary award animation
htmlacademy-animation/1310799-magic-vacation-1 pull request #8
Opened 2020-09-06 17:24 UTC by VladimirovaAnastasia

2020-09-19 08:32 UTC, dean992008 requested changes

2020-09-19 08:32 UTC, dean992008 commented on source/scss/blocks/prizes.scss
> +    animation-delay: 4000ms;
У Вас установлена зажержка анимации появления 4сек., по при этом анимация внутри SVG проигрываеться сразу, в итоге чемодан показываеться уже сразу в финальном состоянии. 
https://fex.net/ru/s/znlk7af

UPD: Если перезагрузить страницу сразу на призах, то все ок, поэтому проблему нужно искать именно в смене экрана.

2020-09-19 08:32 UTC, dean992008 commented on source/js/script.js
> +    setTimeout(() => {
Зачем Вам здесь пустой timeOut думаю он не нужен.

2020-09-19 08:32 UTC, dean992008 commented on source/img/secondary-award-from.svg
> +  <g id="plant">
Этот файл нигде не используеться. Если это так удалите его.

2020-09-19 08:34 UTC, dean992008 commented
Также исправьте, пожалуйста, замечания тревиса: https://travis-ci.com/github/htmlacademy-animation/1310799-magic-vacation-1/builds/182966019 или локально npm test в консоли.

2020-11-19 23:09 UTC, gkarev commented
Анимация описана не корректно, необходимо выставить тайминги, зацепить воспроизведение анимации за класс, переключения экранов. Сейчас при переключении страниц, или обновлении, с сильной задержкой появляется картинка приза, без анимации см. видео в архиве.
[2020-11-20 02-08-02.zip](https://github.com/htmlacademy-animation/1310799-magic-vacation-1/files/5570226/2020-11-20.02-08-02.zip)

2020-11-20 05:29 UTC, VladimirovaAnastasia commented
Что значит, что анимация описана некорректно, в чем это заключается?
Какие тайминги? И куда? 
Я зацепила воспроизведение анимации за переключением между экранами (после экрана история и когда обновляешь страницу, после др экранов пока нет)
Если почистить кеш и впервые открывать страницу с призами, то все работает ок.  А далее я не понимаю, почему оно не хочет заново воспроизводиться, когда перелистываешь (я убираю ссылку на src и по очереди с задержкой вставляю заново и оно по идее с самого начала должна воспроизводиться).

2020-11-20 05:31 UTC, VladimirovaAnastasia commented
> Анимация описана не корректно, необходимо выставить тайминги, зацепить воспроизведение анимации за класс, переключения экранов. Сейчас при переключении страниц, или обновлении, с сильной задержкой появляется картинка приза, без анимации см. видео в архиве.
> [2020-11-20 02-08-02.zip](https://github.com/htmlacademy-animation/1310799-magic-vacation-1/files/5570226/2020-11-20.02-08-02.zip)

Что значит, что анимация описана некорректно, в чем это заключается?
Какие тайминги? И куда?
Я зацепила воспроизведение анимации за переключением между экранами (после экрана история и когда обновляешь страницу, после др экранов пока нет)
Если почистить кеш и впервые открывать страницу с призами, то все работает ок. А далее я не понимаю, почему оно не хочет заново воспроизводиться, когда перелистываешь (я убираю ссылку на src и по очереди с задержкой вставляю заново и оно по идее с самого начала должна воспроизводиться).

2020-11-23 18:58 UTC, merged